[package]
name = "diesel_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="proji"
path="src/lib.rs"

[dependencies]
diesel = { version = "2.1.1", features = ["postgres"] }
dotenvy = "0.15.7"
rocket = { version = "0.5.0-rc.3", features = ["json", "secrets"] }
serde = { version = "1.0.188", features = ["derive"] }
